### ISSUE TITLE
Scratch org is not deleted if CI build fails

### ISSUE THREAD

**Issue by pozil** [trailheadapps/ebikes-lwc#118]
Looking at the current GitHub action config and field experiments, scratch org are not deleted if CI build fails. If a job step fails, the remaining steps are not executed.
The workaround for this is to add an "always" condition to cleanup task like so:

```yml
            # Housekeeping
            - name: 'Delete scratch org'
              if: always()
              uses: forcedotcom/salesforcedx-actions@master
              with:
                  args: 'force:org:delete -p -u quiz-ci'
```

FYI @muenzpraeger this affects all sample apps.
